### ISSUE TITLE
Cannot compile on macOS 10.12, 

### ISSUE THREAD

**Issue by hvze** [aseprite/aseprite#1655]
Describe your bug report or feature request here
When trying to compile Aseprite on my machine, everything goes well until we get to the skia part. I get this error:
```fatal: unable to access 'https://skia.googlesource.com/third_party/harfbuzz.git/': Server aborted the SSL handshake
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 132, in git_checkout_to_directory
    [git, 'clone', '--quiet', repo, directory])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/third_party/harfbuzz.git', 'third_party/externals/harfbuzz']' returned non-zero exit status 128```



### Aseprite and System version

* Aseprite version: (latest as of date, will update when not in class), Installer?
* System: macOS, 10.12

**Comment by hvze** [comment]
I'm also pretty sure I saw a SSL error in there too, can't find it though.

**Comment by dacap** [comment]
It looks like a problem where the skia repo wasn't completely synced. Try running

    python tools/git-sync-deps

again in the skia directory until it doesn't fail.

**Comment by hvze** [comment]
```fatal: unable to access 'https://skia.googlesource.com/third_party/libjpeg-turbo.git/': Server aborted the SSL handshake
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 132, in git_checkout_to_directory
    [git, 'clone', '--quiet', repo, directory])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/third_party/libjpeg-turbo.git', 'third_party/externals/libjpeg-turbo']' returned non-zero exit status 128
```

This is what I get after running a third time.
