### ISSUE TITLE
Can't generate Skia build files?

### ISSUE THREAD

**Issue by Nikitaw99** [aseprite/aseprite#1806]
When I try to run the command `gn gen out/Release --args="is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false target_cpu=""x86"" cc=2017"`, it returns the following:
```
Traceback (most recent call last):
  File "C:/deps/skia/gn/highest_version_dir.py", line 15, in <module>
    print sorted(filter(regex.match, os.listdir(dirpath)))[-1]
WindowsError: [Error 3] : 'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/*.*'
ERROR at //gn/BUILDCONFIG.gn:182:29: Script returned non-zero exit code.
    win_toolchain_version = exec_script("//gn/highest_version_dir.py",
                            ^----------
Current dir: C:/deps/skia/out/Release/
Command: C:/deps/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe -- C:/deps/skia/gn/highest_version_dir.py "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC" "[0-9]{2}\.[0-9]{2}\.[0-9]{5}"
Returned 1.
```

### Aseprite and System version

* Aseprite version: v1.2.9
* System: Windows 10

**Comment by Nikitaw99** [comment]
I believe I found the problem. I was missing one of the dependencies. `Windows 10 SDK`, to be precise.

The build files are being generated properly now.

**Comment by akyd0295** [comment]
i was compiling Aseprite but at   
```
gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
```
i am getting 
```
Traceback (most recent call last):
  File "/home/prog-mark/deps/depot_tools/gn.py", line 72, in <module>
    sys.exit(main(sys.argv))
  File "/home/prog-mark/deps/depot_tools/gn.py", line 67, in main
    return subprocess.call([gn_path] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```
