### ISSUE TITLE
Error on Skia (Linux) - python tools/git-async-deps

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#1922]
running `python tools/git-async-deps` gives this error on linux:
```
File "tools/git-sync-deps", line 209
    print 'Skipping "%s".' % directory
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Skipping "%s".' % directory)?
```
(Maybe this is due to python version?)

fixing the file in `tools/git-async-deps` gives this error however:
```
Traceback (most recent call last):
  File "tools/git-sync-deps", line 253, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 245, in main
    git_sync_deps(deps_file_path, argv, verbose)
  File "tools/git-sync-deps", line 190, in git_sync_deps
    deps_file = parse_file_to_dict(deps_file_path)
  File "tools/git-sync-deps", line 170, in parse_file_to_dict
    execfile(path, dictionary)
NameError: name 'execfile' is not defined
```

**Comment by flamendless** [comment]
Yes, python was the issue. The command should be `python2.7 tools/git-sync-deps`
