### ISSUE TITLE
Installation document out of date?

### ISSUE THREAD

**Issue by leandrinux** [aseprite/aseprite#2238]
I followed step by step the installation instructions under the title `Skia on macOS`, however I got an error. This is the output I get after `python tools/git-sync-deps`:

```
buildtools                           @ e6b510a9daf822bbe9f922c200c58150803d2fd8
common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
third_party/externals/expat          @ android-6.0.1_r55
third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
third_party/externals/angle2         @ ced5c86c3a48ec9934e447e91f78120bb0ae5ee1
third_party/externals/harfbuzz       @ 1.4.2
third_party/externals/freetype       @ 447a0b62634802d8acdb56008cff5ff4e50be244
third_party/externals/jsoncpp        @ 1.0.0
third_party/externals/piex           @ 8f540f64b6c170a16fb7e6e52d61819705c1522a
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/zlib           @ 4576304a4b9835aa8646c9735b079e1d96858633
third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
third_party/externals/sfntly         @ b18b09b6114b9b7fe6fc2f96d8b15e8a72f66916
remote: PERMISSION_DENIED: The caller does not have permission
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "1d4766fdb91b46dfaeb4351add42c290"
fatal: unable to access 'https://skia.googlesource.com/third_party/libjpeg-turbo.git/': The requested URL returned error: 403
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 132, in git_checkout_to_directory
    [git, 'clone', '--quiet', repo, directory])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/third_party/libjpeg-turbo.git', 'third_party/externals/libjpeg-turbo']' returned non-zero exit status 128

third_party/externals/libwebp        @ v0.6.0
```

**Comment by aymansabi** [comment]
Having the same problem, any help?

**Comment by dacap** [comment]
Repeating the command `python tools/git-sync-deps` should work. Anyway if it's related to and old version of Skia, I'll try to update to skia/m81 in these days.
