### ISSUE TITLE
cannot build aseprite cause of skia

### ISSUE THREAD

**Issue by F-r-o-i-d** [aseprite/aseprite#3695]
HI ✋
first of all im french so sorry for my english

 when i try to build skia i have 2 error always the same 

```
(mer. févr.-2 2:15:45)-(CPU 16,8%:0:Net 20)-(wyene:~/dependencies/skia)-(296K:40)
> python2 tools/git-sync-deps
Skipping "../src".
fatal: repository 'https://skia.googlesource.com/common.git/' not found
buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
third_party/externals/opencl-lib     @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
third_party/externals/zlib           @ ea3ba903faac98b64b2bf8de5e98cd97b335a474
third_party/externals/jsoncpp        @ 1.0.0
third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
third_party/externals/Nima-Math-Cpp  @ e0c12772093fa8860f55358274515b86885f0108
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 132, in git_checkout_to_directory
    [git, 'clone', '--quiet', repo, directory])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/common.git', 'common']' returned non-zero exit status 128

```
and when i try to use gn in the skia folder i have this issues 
```
> gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
``` 

btw im on Zorin os but i dont think it could be the issue

thanks you.

**Comment by St0rming** [comment]
.

**Comment by F-r-o-i-d** [comment]
i didnt send you an email :fearful: are you sure its not because you click on the eyes of the project ?

**Comment by Gasparoken** [comment]
You can try copying the pre-built binary packages of the Skia library (https://github.com/aseprite/skia/releases), so you don't need to compile Skia.

**Comment by F-r-o-i-d** [comment]
yep i manage to compile it thanks you
