### ISSUE TITLE
Linux dependencies sync issue

### ISSUE THREAD

**Issue by paneverka** [aseprite/aseprite#4379]
Hello, please 🙏 guide if I am doing anything wrong. Executing `python3 tools/git-sync-deps` results in:
```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2723 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Exception in thread Thread-11 (git_checkout_to_directory):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/usr/deps/skia/tools/git-sync-deps", line 134, in git_checkout_to_directory
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', '--no-checkout', 'https://github.com/aseprite/freetype2.git', '/home/usr/deps/skia/third_party/externals/freetype']' returned non-zero exit status 128.
```
Did several attempts, always getting the same error. Other dependencies are fetched without issues during the first run. Running `python3 tools/git-sync-deps` for a second time fixes the problem with the **freetype**, and I get:
 ```
 ..ia/third_party/externals/freetype > f122349b937d7d2b0f8b72f46f60a082ca6006db
 ```
However, in 🔗 https://github.com/google/skia/blob/main/DEPS another commit ([click](https://chromium.googlesource.com/chromium/src/third_party/freetype2.git/+/f42ce25563b73fed0123d18a2556b9ba01d2c76b)) is mentioned:
```
"third_party/externals/freetype"               : "https://chromium.googlesource.com/chromium/src/third_party/freetype2.git@f42ce25563b73fed0123d18a2556b9ba01d2c76b",
```
Have some doubts, that it is a network issue 🤔 (http.postBuffer is not set). Maybe something is wrong with the https://github.com/aseprite/freetype2.git ?

---
### Aseprite and System version

* Aseprite version: v1.3.3, compiling
* System: Linux, Ubuntu 23.10
* Skia: aseprite-m102 branch
* Python: 3.11.6
---

**Comment by dacap** [comment]
Hi @paneverka, the f122349b937d7d2b0f8b72f46f60a082ca6006db is a commit in our freetype2 fork:
https://github.com/aseprite/freetype2/commit/f122349b937d7d2b0f8b72f46f60a082ca6006db
Specified in our fork of skia: https://github.com/aseprite/skia/blob/aseprite-m102/DEPS

You said that running the sync command fixed the issue, but then did you get other error?

**Comment by paneverka** [comment]
Hi @dacap, thanks for the response. The app builds and launches fine. As a workaround, I just do:
```
python3 tools/git-sync-deps && \
python3 tools/git-sync-deps && \
```

In the first run I always get:
```
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
...
subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', '--no-checkout', 'https://github.com/aseprite/freetype2.git', '/home/usr/deps/skia/third_party/externals/freetype']' returned non-zero exit status 128.
```
After the `python3 tools/git-sync-deps` runs for the second time, the error disappears and I get:
```
...
...ps/skia/third_party/externals/icu @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
...ia/third_party/externals/freetype > f122349b937d7d2b0f8b72f46f60a082ca6006db
```
The hashes for all dependencies match with the ones listed in the `DEPS`, only the **freetype** fails and is updated with the `> f122349b937d7d2b0f8b72f46f60a082ca6006db`.
